# Generated by Django 3.2 on 2022-12-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_on']},
        ),
    ]
