# Generated by Django 3.2 on 2022-12-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20221218_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requirements',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
